query GetCollection($ministry: ID!, $type: String) {
  ministry(id: $ministry) {
    collections(type: $type) {
      edges {
        node {
          id
          title
          links {
            totalCount
          }
        }
      }
    }
  }
}
